### ISSUE TITLE
Cannot find relationship with type STATE_OF 

### ISSUE THREAD

**Issue by vishal-android-freak** [adam-cowley/neode#105]
**My State.ts file**

```javascript
export default  {
    id: {
        primary: true,
        type: 'uuid'
    },
    name: {
        type: 'string',
        empty: false,
    },
    countryRel: {
        type: 'relationship',
        target: 'Country',
        relationship: 'STATE_OF',
        direction: 'out'
    },
    country: {
        type: 'node',
        target: 'Country',
        relationship: 'STATE_OF',
        direction: 'out',
        eager: true
    }
};
```
My  Country.ts file
```javascript
export default  {
    id: {
        primary: true,
        type: 'uuid'
    },
    name: {
        type: 'string',
        empty: false,
    }
};
```

**Here is my code for creating state and relationship**
```javascript
const country = await neo4j.first('Country', 'id', input.countryId);
                if (country) {
                    const state = await neo4j.create('State', {
                        name: input.name
                    });
                    console.log(state);
                    await state.relateTo(country, 'STATE_OF');
              }
```

But I am getting this error
`"Cannot find relationship with type STATE_OF"`

What am I missing here?

**Comment by pihomeserver** [comment]
Try replacing STATE_OF with country
You have to specify the related property of the model, not the relationship name

**Comment by vishal-android-freak** [comment]
@pihomeserver Thanks brother :) Saved hours!

**Comment by jdarosaj** [comment]
> @pihomeserver Thanks brother :) Saved hours!

Can you tell what you've changed? I've the same error, but success here...

**Comment by ryandeklerk** [comment]
For anyone who may find this in the future, I'll try to explain the solution with more detail. In the above State.ts file, OP has defined a relationship called `country`:

```
country: {
        type: 'node',
        target: 'Country',
        relationship: 'STATE_OF',
        direction: 'out',
        eager: true
    }
```
OP was trying to use the `.relateTo()` method with the `relationship` property of the model's `country` object. This is what I thought you're supposed to do as well, based on what documentation exists. But what you're actually supposed to do in the `.relateTo()` method is use a string that represents the name of the object that defines the relationship. So instead of `state.relateTo(country, 'STATE_OF')`, the solution is `state.relateTo(country, 'country')`, as `country` is the name of the relationship object.

The `relationship` property within the named object is what you want the relationship to be called in Neo4j.
