### ISSUE TITLE
[Bug] Provided Object to Create fails validation

### ISSUE THREAD

**Issue by gooftroop** [adam-cowley/neode#21]
For the following code:
```
neode.model(LABEL).create(data);
```

where `data` is an object (i.e. `{ foo: 'bar' }`), `create` throws a validation error from `GenerateDefaultValues` saying that `properties is not an object`. This is due to the following check:
```
if (!(properties instanceof Object)) { ... }
```

I believe this should be the following instead:
```
if (!typeof properties === 'object' || Array.isArray(properties)) { ... }
```

(You can also use `assert` to provide a cleaner read on your validation)

**Comment by gooftroop** [comment]
As a note, if I destructure the object `data` that I'm provided to a new object, the validation passes.

**Comment by gooftroop** [comment]
looks like this fails when you pass `create` (or any model method) a nested object. i.e. In my case:
```
neode.model(LABEL).create(args.data);
```

**Comment by adam-cowley** [comment]
What was the original `args` object that caused the error?  At the moment you can only pass through a single object to `create()` rather than an array.  You'll need to pass through the properties at root level otherwise it'll think that `data` is a property.

It may get tricky if you were expecting a Node to be returned but instead received a Collection.  You could use Promise.all() to create multiple but that would be inefficient. Maybe there needs to be a createMultiple method?

**Comment by gooftroop** [comment]
```
args.data = {
  location: {
    longitude: <float>,
    latitude: <float>,
  },
  userId: 1,
}
```

So I had the following in my code:

`const result = await neo4j.model(LABEL).create(args.data);`
