### ISSUE TITLE
How to seed data using neode?

### ISSUE THREAD

**Issue by anistark** [adam-cowley/neode#70]
I want to seed the initial data before starting my server.

**Comment by adam-cowley** [comment]
There isn't anything specifically to seed a database in neode.  What kind of data do you want to create?  

You could create a seed.js file and use neode to create nodes or use LOAD CSV to load the data directly into neo4j using cypher.

Neode will create indexes and constraints for you if you run:

```
neode.schema.install()
```

**Comment by anistark** [comment]
It can be in json format even.
I can of course write a loop to create each record synchronously. 

Just wanted to know if I do something like say `./node_modules/bin/neode --seed seed.json` 


Could you give an example of how `neode.schema.install()` works? Couldn't find it in documentation.

**Comment by adam-cowley** [comment]
`neode.schema.install()` will scan the models for primary keys, indexes, required etc and run the appropriate `CREATE CONSTRAINT`/`CREATE INDEX` commands on the db.

As for seeding, LOAD CSV directly into Neo4j would be perfect for this.  Otherwise, you could write some javascript to batch the nodes, then  `UNWIND` them in a cypher query.

https://neo4j.com/developer/guide-import-csv/
https://medium.com/neo4j/5-tips-tricks-for-fast-batched-updates-of-graph-structures-with-neo4j-and-cypher-73c7f693c8cc
